export const START_TRAINING_NAME = 'START_TRAINING_NAME';
export const START_EXAM_NAME = 'START_EXAM_NAME';
export const RESTART_QUESTIONS_NAME = 'RESTART_QUESTIONS_NAME';
export const ANSWER_QUESTION_NAME = 'ANSWER_QUESTION_NAME';
export const CONFIRM_CORRECT_NAME = 'CONFIRM_CORRECT_NAME';
export const OPEN_NEXT_QUESTION_NAME = 'OPEN_NEXT_QUESTION_NAME';
