import type { Karuta, KarutaNo } from '@/domains/models';

export const KARUTA_LIST: ReadonlyArray<Karuta> = [
  {
    no: 1 as KarutaNo,
    creator: '天智天皇',
    shoku: {
      kana: 'あきのたの',
      kanji: '秋の田の',
    },
    niku: {
      kana: 'かりほのいほの',
      kanji: 'かりほの庵の',
    },
    sanku: {
      kana: 'とまをあらみ',
      kanji: '苫をあらみ',
    },
    shiku: {
      kana: 'わがころもでは',
      kanji: 'わが衣手は',
    },
    kekku: {
      kana: 'つゆにぬれつつ',
      kanji: '露にぬれつつ',
    },
    translation:
      '秋の田の側につくった仮小屋に泊まってみると、屋根をふいた苫の目があらいので、その隙間から忍びこむ冷たい夜露が、私の着物の袖をすっかりと濡らしてしまっているなぁ。',
    imageNo: '001',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 2 as KarutaNo,
    creator: '持統天皇',
    shoku: {
      kana: 'はるすぎて',
      kanji: '春すぎて',
    },
    niku: { kana: 'なつきにけらし', kanji: '夏来にけらし' },
    sanku: { kana: 'しろたへの', kanji: '白妙の' },
    shiku: { kana: 'ころもほすてふ', kanji: '衣ほすてふ' },
    kekku: { kana: 'あまのかぐやま', kanji: '天の香具山' },
    translation:
      'もう春は過ぎ去り、いつのまにか夏が来てしまったようですね。香具山には、あんなにたくさんのまっ白な着物が干されているのですから。',
    imageNo: '002',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 3 as KarutaNo,
    creator: '柿本人麻呂',
    shoku: { kana: 'あしびきの', kanji: 'あしびきの' },
    niku: { kana: 'やまどりのをの', kanji: '山鳥の尾の' },
    sanku: { kana: 'しだりをの', kanji: 'しだり尾の' },
    shiku: { kana: 'ながながしよを', kanji: 'ながながし夜を' },
    kekku: { kana: 'ひとりかもねむ', kanji: 'ひとりかも寝む' },
    translation:
      '夜になると、雄と雌が離れて寝るという山鳥だが、その山鳥の長く垂れ下がった尾のように、こんなにも長い長い夜を、私もまた、(あなたと離れて)ひとり寂しく寝るのだろうか。',
    imageNo: '003',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 4 as KarutaNo,
    creator: '山部赤人',
    shoku: { kana: 'たごのうらに', kanji: '田子の浦に' },
    niku: { kana: 'うちいでてみれば', kanji: 'うち出でてみれば' },
    sanku: { kana: 'しろたへの', kanji: '白妙の' },
    shiku: { kana: 'ふじのたかねに', kanji: '富士のたかねに' },
    kekku: { kana: 'ゆきはふりつつ', kanji: '雪は降りつつ' },
    translation:
      '田子の浦の海岸に出てみると､雪をかぶったまっ白な富士の山が見事に見えるが、その高い峰には、今もしきりに雪がふり続けている。(あぁ、なんと素晴らしい景色なのだろう)',
    imageNo: '004',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 5 as KarutaNo,
    creator: '猿丸大夫',
    shoku: { kana: 'おくやまに', kanji: '奥山に' },
    niku: { kana: 'もみぢふみわけ', kanji: '紅葉踏み分け' },
    sanku: { kana: 'なくしかの', kanji: '鳴く鹿の' },
    shiku: { kana: 'こゑきくときぞ', kanji: '声聞くときぞ' },
    kekku: { kana: 'あきはかなしき', kanji: '秋は悲しき' },
    translation:
      '奥深い山の中で､(一面に散りしいた)紅葉をふみわけて鳴いている鹿の声を聞くときは､この秋の寂しさが、いっそう悲しく感じられることだ。',
    imageNo: '005',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 6 as KarutaNo,
    creator: '中納言家持',
    shoku: { kana: 'かささぎの', kanji: '鵲の' },
    niku: { kana: 'わたせるはしに', kanji: '渡せる橋に' },
    sanku: { kana: 'おくしもの', kanji: '置く霜の' },
    shiku: { kana: 'しろきをみれば', kanji: '白きを見れば' },
    kekku: { kana: 'よぞふけにける', kanji: '夜ぞふけにける' },
    translation:
      'かささぎが渡したという天上の橋のように見える宮中の階段であるが、その上に降りた真っ白い霜を見ると､夜も随分と更けたのだなあ｡',
    imageNo: '006',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 7 as KarutaNo,
    creator: '阿倍仲麻呂',
    shoku: { kana: 'あまのはら', kanji: '天の原' },
    niku: { kana: 'ふりさけみれば', kanji: 'ふりさけ見れば' },
    sanku: { kana: 'かすがなる', kanji: '春日なる' },
    shiku: { kana: 'みかさのやまに', kanji: '三笠の山に' },
    kekku: { kana: 'いでしつきかも', kanji: '出でし月かも' },
    translation:
      '大空を振り仰いで眺めると､美しい月が出ているが、あの月はきっと故郷である春日の三笠の山に出た月と同じ月だろう。(ああ､本当に恋しいことだなあ)',
    imageNo: '007',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 8 as KarutaNo,
    creator: '喜撰法師',
    shoku: { kana: 'わがいほは', kanji: 'わが庵は' },
    niku: { kana: 'みやこのたつみ', kanji: '都のたつみ' },
    sanku: { kana: 'しかぞすむ', kanji: 'しかぞすむ' },
    shiku: { kana: 'よをうぢやまと', kanji: '世をうぢ山と' },
    kekku: { kana: 'ひとはいふなり', kanji: '人はいふなり' },
    translation:
      '私の草庵は都の東南にあって、そこで静かにくらしている。しかし世間の人たちは(私が世の中から隠れ)この宇治の山に住んでいるのだと噂しているようだ。',
    imageNo: '008',
    kimariji: 3,
    color: 'green',
  },
  {
    no: 9 as KarutaNo,
    creator: '小野小町',
    shoku: { kana: 'はなのいろは', kanji: '花の色は' },
    niku: { kana: 'うつりにけりな', kanji: '移りにけりな' },
    sanku: { kana: 'いたづらに', kanji: 'いたづらに' },
    shiku: { kana: 'わがみよにふる', kanji: '我身世にふる' },
    kekku: { kana: 'ながめせしまに', kanji: 'ながめせしまに' },
    translation:
      '花の色もすっかり色あせてしまいました。降る長雨をぼんやりと眺めいるうちに。\r(わたしの美しさも、その花の色のように、こんなにも褪せてしまいました)',
    imageNo: '009',
    kimariji: 3,
    color: 'green',
  },
  {
    no: 10 as KarutaNo,
    creator: '蝉丸',
    shoku: { kana: 'これやこの', kanji: 'これやこの' },
    niku: { kana: 'ゆくもかへるも', kanji: '行くも帰るも' },
    sanku: { kana: 'わかれては', kanji: '別れては' },
    shiku: { kana: 'しるもしらぬも', kanji: '知るも知らぬも' },
    kekku: { kana: 'あふさかのせき', kanji: 'あふ坂の関' },
    translation:
      'これがあの有名な、(東国へ)下って行く人も都へ帰る人も、ここで別れてはまたここで会い、知っている人も知らない人も、またここで出会うという逢坂の関なのだなあ｡',
    imageNo: '010',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 11 as KarutaNo,
    creator: '参議篁',
    shoku: { kana: 'わたのはら', kanji: 'わたの原' },
    niku: { kana: 'やそしまかけて', kanji: '八十島かけて' },
    sanku: { kana: 'こぎいでぬと', kanji: '漕き出でぬと' },
    shiku: { kana: 'ひとにはつげよ', kanji: '人には告げよ' },
    kekku: { kana: 'あまのつりぶね', kanji: 'あまのつりぶね' },
    translation:
      '(篁は)はるか大海原を多くの島々目指して漕ぎ出して行ったと､都にいる親しい人に告げてくれないか、そこの釣舟の漁夫よ｡',
    imageNo: '011',
    kimariji: 6,
    color: 'green',
  },
  {
    no: 12 as KarutaNo,
    creator: '僧正遍昭',
    shoku: { kana: 'あまつかぜ', kanji: '天つ風' },
    niku: { kana: 'くものかよひぢ', kanji: '雲のかよひ路' },
    sanku: { kana: 'ふきとぢよ', kanji: '吹きとぢよ' },
    shiku: { kana: 'をとめのすがた', kanji: '乙女の姿' },
    kekku: { kana: 'しばしとどめむ', kanji: 'しばしとどめむ' },
    translation:
      '空吹く風よ､雲の中にあるという(天に通じる)道を吹いて閉じてくれないか。(天に帰っていく)乙女たちの姿を、しばらくここに引き留めておきたいから｡',
    imageNo: '012',
    kimariji: 3,
    color: 'blue',
  },
  {
    no: 13 as KarutaNo,
    creator: '陽成院',
    shoku: { kana: 'つくばねの', kanji: '筑波嶺の' },
    niku: { kana: 'みねよりおつる', kanji: 'みねより落つる' },
    sanku: { kana: 'みなのがは', kanji: 'みなの川' },
    shiku: { kana: 'こひぞつもりて', kanji: '恋ぞつもりて' },
    kekku: { kana: 'ふちとなりぬる', kanji: '淵となりぬる' },
    translation:
      '筑波山の峯から流れてくるみなの川も、(最初は小さなせせらぎほどだが)やがては深い淵をつくるように､私の恋もしだいに積もり､今では淵のように深いものとなってしまった｡',
    imageNo: '013',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 14 as KarutaNo,
    creator: '河原左大臣',
    shoku: { kana: 'みちのくの', kanji: '陸奥の' },
    niku: { kana: 'しのぶもぢずり', kanji: 'しのぶもぢずり' },
    sanku: { kana: 'たれゆゑに', kanji: '誰ゆゑに' },
    shiku: { kana: 'みだれそめにし', kanji: '乱れそめにし' },
    kekku: { kana: 'われならなくに', kanji: '我ならなくに' },
    translation:
      '奥州のしのぶもじずりの乱れ模様のように､私の心も(恋のために)乱れていますが､いったい誰のためにこのように思い乱れているのでしょう｡ (きっとあなたの所為に違いありません)',
    imageNo: '014',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 15 as KarutaNo,
    creator: '光孝天皇',
    shoku: { kana: 'きみがため', kanji: '君がため' },
    niku: { kana: 'はるののにいでて', kanji: '春の野にいでて' },
    sanku: { kana: 'わかなつむ', kanji: '若菜摘む' },
    shiku: { kana: 'わがころもでに', kanji: 'わが衣手に' },
    kekku: { kana: 'ゆきはふりつつ', kanji: '雪は降りつつ' },
    translation:
      'あなたのために春の野に出て若菜を摘んでいましたが､春だというのにちらちらと雪が降ってきて、私の着物の袖にも雪が降りかかっています｡　(それでも、あなたのことを思いながら、こうして若菜を摘んでいるのです)',
    imageNo: '015',
    kimariji: 6,
    color: 'green',
  },
  {
    no: 16 as KarutaNo,
    creator: '中納言行平',
    shoku: { kana: 'たちわかれ', kanji: '立ち別れ' },
    niku: { kana: 'いなばのやまの', kanji: 'いなばの山の' },
    sanku: { kana: 'みねにおふる', kanji: '峰に生ふる' },
    shiku: { kana: 'まつとしきかば', kanji: 'まつとし聞かば' },
    kekku: { kana: 'いまかへりこむ', kanji: '今帰り来む' },
    translation:
      'あなたと別れて(因幡の国へ)行くけれども､稲葉の山の峰に生えている松のように､あなたが待っていると聞いたなら､すぐにも都に帰ってまいりましょう｡',
    imageNo: '016',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 17 as KarutaNo,
    creator: '在原業平朝臣',
    shoku: { kana: 'ちはやぶる', kanji: 'ちはやぶる' },
    niku: { kana: 'かみよもきかず', kanji: '神代もきかず' },
    sanku: { kana: 'たつたがは', kanji: '竜田川' },
    shiku: { kana: 'からくれなゐに', kanji: 'からくれなゐに' },
    kekku: { kana: 'みづくくるとは', kanji: '水くくるとは' },
    translation:
      '(川面に紅葉が流れていますが)神代の時代にさえこんなことは聞いたことがありません。竜田川一面に紅葉が散りしいて、流れる水を鮮やかな紅の色に染めあげるなどということは。',
    imageNo: '017',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 18 as KarutaNo,
    creator: '藤原敏行朝臣',
    shoku: { kana: 'すみのえの', kanji: '住の江の' },
    niku: { kana: 'きしによるなみ', kanji: '岸に寄る波' },
    sanku: { kana: 'よるさへや', kanji: 'よるさへや' },
    shiku: { kana: 'ゆめのかよひぢ', kanji: '夢のかよひ路' },
    kekku: { kana: 'ひとめよくらむ', kanji: '人目よくらむ' },
    translation:
      '住の江の岸に打ち寄せる波のように (いつもあなたに会いたいのだが)、 どうして夜の夢の中でさえ､あなたは人目をはばかって会ってはくれないのだろう。',
    imageNo: '018',
    kimariji: 1,
    color: 'yellow',
  },
  {
    no: 19 as KarutaNo,
    creator: '伊勢',
    shoku: { kana: 'なにはがた', kanji: '難波潟' },
    niku: { kana: 'みじかきあしの', kanji: '短かき蘆の' },
    sanku: { kana: 'ふしのまも', kanji: '節の間も' },
    shiku: { kana: 'あはでこのよを', kanji: '逢はでこの世を' },
    kekku: { kana: 'すぐしてよとや', kanji: '過ぐしてよとや' },
    translation:
      '難波潟の入り江に茂っている芦の、短い節と節の間のような短い時間でさえお会いしたいのに、それも叶わず、この世を過していけとおっしゃるのでしょうか。',
    imageNo: '019',
    kimariji: 4,
    color: 'orange',
  },
  {
    no: 20 as KarutaNo,
    creator: '元良親王',
    shoku: { kana: 'わびぬれば', kanji: 'わびぬれば' },
    niku: { kana: 'いまはたおなじ', kanji: '今はた同じ' },
    sanku: { kana: 'なにはなる', kanji: '難波なる' },
    shiku: { kana: 'みをつくしても', kanji: '身をつくしても' },
    kekku: { kana: 'あはむとぞおもふ', kanji: '逢はむとぞ思ふ' },
    translation:
      '(あなたにお逢いできなくて) このように思いわびて暮らしていると､今はもう身を捨てたのと同じことです｡いっそのこと、あの難波のみおつくしのように､この身を捨ててもお会いしたいと思っています｡',
    imageNo: '020',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 21 as KarutaNo,
    creator: '素性法師',
    shoku: { kana: 'いまこむと', kanji: '今来むと' },
    niku: { kana: 'いひしばかりに', kanji: 'いひしばかりに' },
    sanku: { kana: 'ながつきの', kanji: '長月の' },
    shiku: { kana: 'ありあけのつきを', kanji: '有明の月を' },
    kekku: { kana: 'まちいでつるかな', kanji: '待ち出でつるかな' },
    translation:
      '「今すぐに行きましょう」とあなたがおっしゃったので、(その言葉を信じて) 九月の長い夜を待っていましたが、とうとう有明の月が出る頃を迎えてしまいました。',
    imageNo: '021',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 22 as KarutaNo,
    creator: '文屋康秀',
    shoku: { kana: 'ふくからに', kanji: '吹くからに' },
    niku: { kana: 'あきのくさきの', kanji: '秋の草木の' },
    sanku: { kana: 'しをるれば', kanji: 'しをるれば' },
    shiku: { kana: 'むべやまかぜを', kanji: 'むべ山風を' },
    kekku: { kana: 'あらしといふらむ', kanji: 'あらしといふらむ' },
    translation:
      '山風が吹きおろしてくると、たちまち秋の草や木が萎れてしまうので､きっと山風のことを「嵐(荒らし)」いうのだろう｡',
    imageNo: '022',
    kimariji: 1,
    color: 'pink',
  },
  {
    no: 23 as KarutaNo,
    creator: '大江千里',
    shoku: { kana: 'つきみれば', kanji: '月見れば' },
    niku: { kana: 'ちぢにものこそ', kanji: 'ちぢに物こそ' },
    sanku: { kana: 'かなしけれ', kanji: '悲しけれ' },
    shiku: { kana: 'わがみひとつの', kanji: 'わが身ひとつの' },
    kekku: { kana: 'あきにはあらねど', kanji: '秋にはあらねど' },
    translation:
      '秋の月を眺めてていると､様々と思い起こされ物悲しいことです｡秋はわたしひとりだけにやって来たのではないのですが。',
    imageNo: '023',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 24 as KarutaNo,
    creator: '菅家',
    shoku: { kana: 'このたびは', kanji: 'このたびは' },
    niku: { kana: 'ぬさもとりあへず', kanji: 'ぬさもとりあへず' },
    sanku: { kana: 'たむけやま', kanji: '手向山' },
    shiku: { kana: 'もみぢのにしき', kanji: '紅葉のにしき' },
    kekku: { kana: 'かみのまにまに', kanji: '神のまにまに' },
    translation:
      '今度の旅は急いで発ちましたので、捧げるぬさを用意することも出来ませんでした。しかし、この手向山の美しい紅葉をぬさとして捧げますので、どうかお心のままにお受け取りください。',
    imageNo: '024',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 25 as KarutaNo,
    creator: '三条右大臣',
    shoku: { kana: 'なにしおはば', kanji: '名にし負はば' },
    niku: { kana: 'あふさかやまの', kanji: '逢坂山の' },
    sanku: { kana: 'さねかづら', kanji: 'さねかづら' },
    shiku: { kana: 'ひとにしられで', kanji: '人に知られで' },
    kekku: { kana: 'くるよしもがな', kanji: 'くるよしもがな' },
    translation:
      '「逢う」という名の逢坂山､「さ寝」という名のさねかずらが､その名に違わぬのであれば､逢坂山のさねかずらを手繰り寄せるように､あなたのもとにいく方法を知りたいものです。',
    imageNo: '025',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 26 as KarutaNo,
    creator: '貞信公',
    shoku: { kana: 'をぐらやま', kanji: '小倉山' },
    niku: { kana: 'みねのもみぢば', kanji: '峰の紅葉ば' },
    sanku: { kana: 'こころあらば', kanji: '心あらば' },
    shiku: { kana: 'いまひとたびの', kanji: '今ひとたびの' },
    kekku: { kana: 'みゆきまたなむ', kanji: 'みゆき待たなむ' },
    translation:
      '小倉山の峰の美しい紅葉の葉よ､もしお前に哀れむ心があるならば､散るのを急がず、もう一度の行幸をお待ち申していてくれないか｡',
    imageNo: '026',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 27 as KarutaNo,
    creator: '中納言兼輔',
    shoku: { kana: 'みかのはら', kanji: 'みかの原' },
    niku: { kana: 'わきてながるる', kanji: 'わきて流るる' },
    sanku: { kana: 'いづみがは', kanji: 'いづみ川' },
    shiku: { kana: 'いつみきとてか', kanji: 'いつ見きとてか' },
    kekku: { kana: 'こひしかるらむ', kanji: '恋しかるらむ' },
    translation:
      'みかの原を湧き出て流れる泉川よ､(その｢いつ｣という言葉ではないが) その人をいつ見たといっては、恋しく思ってしまう。本当は一度たりとも見たこともないのに。',
    imageNo: '027',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 28 as KarutaNo,
    creator: '源宗于朝臣',
    shoku: { kana: 'やまざとは', kanji: '山里は' },
    niku: { kana: 'ふゆぞさびしさ', kanji: '冬ぞさびしさ' },
    sanku: { kana: 'まさりける', kanji: 'まさりける' },
    shiku: { kana: 'ひとめもくさも', kanji: '人目も草も' },
    kekku: { kana: 'かれぬとおもへば', kanji: 'かれぬと思へば' },
    translation:
      '山里はいつの季節でも寂しいが、冬はとりわけ寂しく感じられる｡尋ねてくれる人も途絶え､慰めの草も枯れてしまうのだと思うと｡',
    imageNo: '028',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 29 as KarutaNo,
    creator: '凡河内躬恒',
    shoku: { kana: 'こころあてに', kanji: '心あてに' },
    niku: { kana: 'をらばやをらむ', kanji: '折らばや折らむ' },
    sanku: { kana: 'はつしもの', kanji: '初霜の' },
    shiku: { kana: 'おきまどはせる', kanji: '置きまどはせる' },
    kekku: { kana: 'しらぎくのはな', kanji: '白菊の花' },
    translation:
      '無造作に折ろうとすれば、果たして折れるだろうか。一面に降りた初霜の白さに、いずれが霜か白菊の花か見分けもつかないほどなのに。',
    imageNo: '029',
    kimariji: 4,
    color: 'green',
  },
  {
    no: 30 as KarutaNo,
    creator: '壬生忠岑',
    shoku: { kana: 'ありあけの', kanji: '有明の' },
    niku: { kana: 'つれなくみえし', kanji: 'つれなく見えし' },
    sanku: { kana: 'わかれより', kanji: '別れより' },
    shiku: { kana: 'あかつきばかり', kanji: '暁ばかり' },
    kekku: { kana: 'うきものはなし', kanji: '憂きものはなし' },
    translation:
      'あなたと別れたあの時も、有明の月が残っていましたが、(別れの時のあなたはその有明の月のようにつれないものでしたが) あなたと別れてからというもの、今でも有明の月がかかる夜明けほどつらいものはありません。',
    imageNo: '030',
    kimariji: 3,
    color: 'blue',
  },
  {
    no: 31 as KarutaNo,
    creator: '坂上是則',
    shoku: { kana: 'あさぼらけ', kanji: '朝ぼらけ' },
    niku: { kana: 'ありあけのつきと', kanji: '有明の月と' },
    sanku: { kana: 'みるまでに', kanji: '見るまでに' },
    shiku: { kana: 'よしののさとに', kanji: '吉野の里に' },
    kekku: { kana: 'ふれるしらゆき', kanji: '降れる白雪' },
    translation:
      '夜が明ける頃あたりを見てみると､まるで有明の月が照らしているのかと思うほどに、吉野の里には白雪が降り積もっているではないか。',
    imageNo: '031',
    kimariji: 6,
    color: 'blue',
  },
  {
    no: 32 as KarutaNo,
    creator: '春道列樹',
    shoku: { kana: 'やまがはに', kanji: '山川に' },
    niku: { kana: 'かぜのかけたる', kanji: '風のかけたる' },
    sanku: { kana: 'しがらみは', kanji: 'しがらみは' },
    shiku: { kana: 'ながれもあへぬ', kanji: '流れもあへぬ' },
    kekku: { kana: 'もみぢなりけり', kanji: '紅葉なりけり' },
    translation:
      '山あいの谷川に、風が架け渡したなんとも美しい柵があったのだが、それは (吹き散らされたままに) 流れきれずにいる紅葉であったではないか｡',
    imageNo: '032',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 33 as KarutaNo,
    creator: '紀友則',
    shoku: { kana: 'ひさかたの', kanji: '久方の' },
    niku: { kana: 'ひかりのどけき', kanji: '光のどけき' },
    sanku: { kana: 'はるのひに', kanji: '春の日に' },
    shiku: { kana: 'しづこころなく', kanji: 'しづ心なく' },
    kekku: { kana: 'はなのちるらむ', kanji: '花の散るらむ' },
    translation:
      'こんなにも日の光が降りそそいでいるのどかな春の日であるのに､どうして落着いた心もなく､花は散っていくのだろうか。',
    imageNo: '033',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 34 as KarutaNo,
    creator: '藤原興風',
    shoku: { kana: 'たれをかも', kanji: '誰をかも' },
    niku: { kana: 'しるひとにせむ', kanji: '知る人にせむ' },
    sanku: { kana: 'たかさごの', kanji: '高砂の' },
    shiku: { kana: 'まつもむかしの', kanji: '松も昔の' },
    kekku: { kana: 'ともならなくに', kanji: '友ならなくに' },
    translation:
      '(友達は次々と亡くなってしまったが) これから誰を友とすればいいのだろう｡馴染みあるこの高砂の松でさえ､昔からの友ではないのだから｡',
    imageNo: '034',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 35 as KarutaNo,
    creator: '紀貫之',
    shoku: { kana: 'ひとはいさ', kanji: '人はいさ' },
    niku: { kana: 'こころもしらず', kanji: '心も知らず' },
    sanku: { kana: 'ふるさとは', kanji: 'ふるさとは' },
    shiku: { kana: 'はなぞむかしの', kanji: '花ぞ昔の' },
    kekku: { kana: 'かににほひける', kanji: '香ににほひける' },
    translation:
      'さて、あなたの心は昔のままであるかどうか分かりません。しかし馴染み深いこの里では、花は昔のままの香りで美しく咲きにおっているではありませんか。(あなたの心も昔のままですよね)',
    imageNo: '035',
    kimariji: 3,
    color: 'green',
  },
  {
    no: 36 as KarutaNo,
    creator: '清原深養父',
    shoku: { kana: 'なつのよは', kanji: '夏の夜は' },
    niku: { kana: 'まだよひながら', kanji: 'まだ宵ながら' },
    sanku: { kana: 'あけぬるを', kanji: '明けぬるを' },
    shiku: { kana: 'くものいづこに', kanji: '雲のいづこに' },
    kekku: { kana: 'つきやどるらむ', kanji: '月宿るらむ' },
    translation:
      '夏の夜は、まだ宵のうちだと思っているのに明けてしまったが、(こんなにも早く夜明けが来れば、月はまだ空に残っているだろうが) いったい月は雲のどの辺りに宿をとっているのだろうか｡',
    imageNo: '036',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 37 as KarutaNo,
    creator: '文屋朝康',
    shoku: { kana: 'しらつゆに', kanji: '白露に' },
    niku: { kana: 'かぜのふきしく', kanji: '風の吹きしく' },
    sanku: { kana: 'あきののは', kanji: '秋の野は' },
    shiku: { kana: 'つらぬきとめぬ', kanji: 'つらぬきとめぬ' },
    kekku: { kana: 'たまぞちりける', kanji: '玉ぞ散りける' },
    translation:
      '(草葉の上に落ちた) 白露に風がしきりに吹きつけている秋の野のさまは､まるで糸に通してとめてない玉が、美しく散り乱れているようではないか｡',
    imageNo: '037',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 38 as KarutaNo,
    creator: '右近',
    shoku: { kana: 'わすらるる', kanji: '忘らるる' },
    niku: { kana: 'みをばおもはず', kanji: '身をば思はず' },
    sanku: { kana: 'ちかひてし', kanji: '誓ひてし' },
    shiku: { kana: 'ひとのいのちの', kanji: '人の命の' },
    kekku: { kana: 'をしくもあるかな', kanji: '惜しくもあるかな' },
    translation:
      'あなたに忘れられる我が身のことは何ほどのこともありませんが､ただ神にかけて (わたしをいつまでも愛してくださると) 誓ったあなたの命が､はたして神罰を受けはしないかと、借しく思われてなりません。',
    imageNo: '038',
    kimariji: 3,
    color: 'green',
  },
  {
    no: 39 as KarutaNo,
    creator: '参議等',
    shoku: { kana: 'あさぢふの', kanji: '浅茅生の' },
    niku: { kana: 'をののしのはら', kanji: '小野の篠原' },
    sanku: { kana: 'しのぶれど', kanji: 'しのぶれど' },
    shiku: { kana: 'あまりてなどか', kanji: 'あまりてなどか' },
    kekku: { kana: 'ひとのこひしき', kanji: '人の恋しき' },
    translation:
      '浅茅の生えた寂しく忍ぶ小野の篠原ではありませんが､あなたへの思いを忍んではいますが､もう忍びきることは出来ません。どうしてこのようにあなたが恋しいのでしょうか｡',
    imageNo: '039',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 40 as KarutaNo,
    creator: '平兼盛',
    shoku: { kana: 'しのぶれど', kanji: '忍ぶれど' },
    niku: { kana: 'いろにいでにけり', kanji: '色に出でにけり' },
    sanku: { kana: 'わがこひは', kanji: 'わが恋は' },
    shiku: { kana: 'ものやおもふと', kanji: '物や思ふと' },
    kekku: { kana: 'ひとのとふまで', kanji: '人の問ふまで' },
    translation:
      '人に知られまいと恋しい思いを隠していたけれど、とうとう隠し切れずに顔色に出てしまったことだ｡何か物思いをしているのではと､人が尋ねるほどまでに。',
    imageNo: '040',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 41 as KarutaNo,
    creator: '壬生忠見',
    shoku: { kana: 'こひすてふ', kanji: '恋すてふ' },
    niku: { kana: 'わがなはまだき', kanji: 'わが名はまだき' },
    sanku: { kana: 'たちにけり', kanji: '立ちにけり' },
    shiku: { kana: 'ひとしれずこそ', kanji: '人知れずこそ' },
    kekku: { kana: 'おもひそめしか', kanji: '思ひそめしか' },
    translation:
      'わたしが恋をしているという噂が、もう世間の人たちの間には広まってしまったようだ。人には知られないよう、密かに思いはじめたばかりなのに。',
    imageNo: '041',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 42 as KarutaNo,
    creator: '清原元輔',
    shoku: { kana: 'ちぎりきな', kanji: '契りきな' },
    niku: { kana: 'かたみにそでを', kanji: 'かたみに袖を' },
    sanku: { kana: 'しぼりつつ', kanji: 'しぼりつつ' },
    shiku: { kana: 'すゑのまつやま', kanji: '末の松山' },
    kekku: { kana: 'なみこさじとは', kanji: '波こさじとは' },
    translation:
      'かたく約束を交わしましたね｡互いに涙で濡れた袖をしぼりながら､波があの末の松山を決して越すことがないように､二人の仲も決して変わることはありますまいと。',
    imageNo: '042',
    kimariji: 4,
    color: 'green',
  },
  {
    no: 43 as KarutaNo,
    creator: '権中納言敦忠',
    shoku: { kana: 'あひみての', kanji: '逢ひ見ての' },
    niku: { kana: 'のちのこころに', kanji: '後の心に' },
    sanku: { kana: 'くらぶれば', kanji: 'くらぶれば' },
    shiku: { kana: 'むかしはものを', kanji: '昔は物を' },
    kekku: { kana: 'おもはざりけり', kanji: '思はざりけり' },
    translation:
      'このようにあなたに逢ってからの今の苦しい恋心にくらべると､会いたいと思っていた昔の恋心の苦しみなどは、何も物思いなどしなかったも同じようなものです。',
    imageNo: '043',
    kimariji: 2,
    color: 'orange',
  },
  {
    no: 44 as KarutaNo,
    creator: '中納言朝忠',
    shoku: { kana: 'あふことの', kanji: '逢ふことの' },
    niku: { kana: 'たえてしなくば', kanji: '絶えてしなくば' },
    sanku: { kana: 'なかなかに', kanji: 'なかなかに' },
    shiku: { kana: 'ひとをもみをも', kanji: '人をも身をも' },
    kekku: { kana: 'うらみざらまし', kanji: '恨みざらまし' },
    translation:
      'あなたと会うことが一度もなかったのならば、むしろあなたのつれなさも、わたしの身の不幸も、こんなに恨むことはなかったでしょうに。(あなたに会ってしまったばっかりに、この苦しみは深まるばかりです)',
    imageNo: '044',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 45 as KarutaNo,
    creator: '謙徳公',
    shoku: { kana: 'あはれとも', kanji: '哀れとも' },
    niku: { kana: 'いふべきひとは', kanji: 'いふべき人は' },
    sanku: { kana: 'おもほえで', kanji: '思ほえで' },
    shiku: { kana: 'みのいたづらに', kanji: '身のいたづらに' },
    kekku: { kana: 'なりぬべきかな', kanji: 'なりぬべきかな' },
    translation:
      '(あなたに見捨てられた) わたしを哀れだと同情を向けてくれそうな人も、今はいように思えません。(このままあなたを恋しながら) 自分の身がむなしく消えていく日を、どうすることもできず、ただ待っているわたしなのです。',
    imageNo: '045',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 46 as KarutaNo,
    creator: '曽禰好忠',
    shoku: { kana: 'ゆらのとを', kanji: '由良の門を' },
    niku: { kana: 'わたるふなびと', kanji: '渡る舟人' },
    sanku: { kana: 'かぢをたえ', kanji: 'かぢを絶え' },
    shiku: { kana: 'ゆくへもしらぬ', kanji: 'ゆくへも知らぬ' },
    kekku: { kana: 'こひのみちかな', kanji: '恋の道かな' },
    translation:
      '由良の海峡を渡る船人が、かいをなくして、行く先も決まらぬままに波間に漂っているように、わたしたちの恋の行方も、どこへ漂っていくのか思い迷っているものだ。',
    imageNo: '046',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 47 as KarutaNo,
    creator: '恵慶法師',
    shoku: { kana: 'やへむぐら', kanji: '八重むぐら' },
    niku: { kana: 'しげれるやどの', kanji: 'しげれる宿の' },
    sanku: { kana: 'さびしきに', kanji: 'さびしきに' },
    shiku: { kana: 'ひとこそみえね', kanji: '人こそ見えね' },
    kekku: { kana: 'あきはきにけり', kanji: '秋は来にけり' },
    translation:
      'このような、幾重にも雑草の生い茂った宿は荒れて寂しく、人は誰も訪ねてはこないが、ここにも秋だけは訪れるようだ。',
    imageNo: '047',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 48 as KarutaNo,
    creator: '源重之',
    shoku: { kana: 'かぜをいたみ', kanji: '風をいたみ' },
    niku: { kana: 'いはうつなみの', kanji: '岩うつ波の' },
    sanku: { kana: 'おのれのみ', kanji: 'おのれのみ' },
    shiku: { kana: 'くだけてものを', kanji: 'くだけて物を' },
    kekku: { kana: 'おもふころかな', kanji: '思ふころかな' },
    translation:
      '風がとても強いので、岩に打ちつける波が、自分ばかりが砕け散ってしまうように、(あなたがとてもつれないので) わたしの心は (恋に悩み) 砕け散るばかりのこの頃です。',
    imageNo: '048',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 49 as KarutaNo,
    creator: '大中臣能宣朝臣',
    shoku: { kana: 'みかきもり', kanji: 'みかきもり' },
    niku: { kana: 'ゑじのたくひの', kanji: '衛士のたく火の' },
    sanku: { kana: 'よるはもえて', kanji: '夜はもえ' },
    shiku: { kana: 'ひるはきえつつ', kanji: '昼は消えつつ' },
    kekku: { kana: 'ものをこそおもへ', kanji: '物をこそ思へ' },
    translation:
      '禁中の御垣を守る衛士のかがり火は、夜は赤々と燃えているが、昼間は消えるようになって、まるで、(夜は情熱に燃え、昼間は思い悩んでいる) わたしの恋の苦しみのようではないか。',
    imageNo: '049',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 50 as KarutaNo,
    creator: '藤原義孝',
    shoku: { kana: 'きみがため', kanji: '君がため' },
    niku: { kana: 'をしからざりし', kanji: '惜しからざりし' },
    sanku: { kana: 'いのちさへ', kanji: '命さへ' },
    shiku: { kana: 'ながくもがなと', kanji: '長くもがなと' },
    kekku: { kana: 'おもひけるかな', kanji: '思ひけるかな' },
    translation:
      'あなたに会うためなら惜しいとは思わなかった私の命ですが、こうしてあなたと会うことができた今は､いつまでも生きていたいと思っています。',
    imageNo: '050',
    kimariji: 6,
    color: 'blue',
  },
  {
    no: 51 as KarutaNo,
    creator: '藤原実方朝臣',
    shoku: { kana: 'かくとだに', kanji: 'かくとだに' },
    niku: { kana: 'えやはいぶきの', kanji: 'えやはいぶきの' },
    sanku: { kana: 'さしもぐさ', kanji: 'さしも草' },
    shiku: { kana: 'さしもしらじな', kanji: 'さしもしらじな' },
    kekku: { kana: 'もゆるおもひを', kanji: '燃ゆる思ひを' },
    translation:
      'これほどまで、あなたを思っているということさえ打ち明けることができずにいるのですから､ましてや伊吹山のさしも草が燃えるように、私の思いもこんなに激しく燃えているとは、あなたは知らないことでしょう。',
    imageNo: '051',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 52 as KarutaNo,
    creator: '藤原道信朝臣',
    shoku: { kana: 'あけぬれば', kanji: '明けぬれば' },
    niku: { kana: 'くるるものとは', kanji: '暮るるものとは' },
    sanku: { kana: 'しりながら', kanji: '知りながら' },
    shiku: { kana: 'なほうらめしき', kanji: 'なほ恨めしき' },
    kekku: { kana: 'あさぼらけかな', kanji: '朝ぼらけかな' },
    translation:
      '夜が明ければ、やがてはまた日が暮れてあなたに会えるものだと分かってはいても、やはりあなたと別れる夜明けは、恨めしく思われるものです。',
    imageNo: '052',
    kimariji: 2,
    color: 'orange',
  },
  {
    no: 53 as KarutaNo,
    creator: '右大将道綱母',
    shoku: { kana: 'なげきつつ', kanji: '嘆きつつ' },
    niku: { kana: 'ひとりぬるよの', kanji: 'ひとり寝る夜の' },
    sanku: { kana: 'あくるまは', kanji: '明くる間は' },
    shiku: { kana: 'いかにひさしき', kanji: 'いかに久しき' },
    kekku: { kana: 'ものとかはしる', kanji: 'ものとかは知る' },
    translation:
      '(あなたが来てくださらないことを) 嘆き哀しみながらひとりで夜をすごす私にとって、夜が明けるのがどれほど長く感じられるものか、あなたはいったいご存じなのでしょうか。',
    imageNo: '053',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 54 as KarutaNo,
    creator: '儀同三司母',
    shoku: { kana: 'わすれじの', kanji: '忘れじの' },
    niku: { kana: 'ゆくすゑまでは', kanji: '行末までは' },
    sanku: { kana: 'かたければ', kanji: 'かたければ' },
    shiku: { kana: 'けふをかぎりの', kanji: '今日を限りの' },
    kekku: { kana: 'いのちともがな', kanji: '命ともがな' },
    translation:
      'いつまでも忘れまいとすることは、遠い将来まではとても難しいものですから､(あなたの心変わりを見るよりも早く) いっそのこと、今日を最後に私の命が終わって欲しいものです。',
    imageNo: '054',
    kimariji: 3,
    color: 'green',
  },
  {
    no: 55 as KarutaNo,
    creator: '大納言公任',
    shoku: { kana: 'たきのおとは', kanji: '滝の音は' },
    niku: { kana: 'たえてひさしく', kanji: '絶えて久しく' },
    sanku: { kana: 'なりぬれど', kanji: 'なりぬれど' },
    shiku: { kana: 'なこそながれて', kanji: '名こそ流れて' },
    kekku: { kana: 'なほきこえけれ', kanji: 'なほ聞えけれ' },
    translation:
      '水の流れが絶えて滝音が聞こえなくなってから、もう長い月日が過ぎてしまったが、(見事な滝であったと) その名は今も伝えられ、よく世間にも知れ渡っていることだ。',
    imageNo: '055',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 56 as KarutaNo,
    creator: '和泉式部',
    shoku: { kana: 'あらざらむ', kanji: 'あらざらむ' },
    niku: { kana: 'このよのほかの', kanji: 'この世のほかの' },
    sanku: { kana: 'おもひでに', kanji: '思ひ出に' },
    shiku: { kana: 'いまひとたびの', kanji: 'いまひとたびの' },
    kekku: { kana: 'あふこともがな', kanji: '逢ふこともがな' },
    translation:
      '私はもうすぐ死んでしまうことでしょうが、私のあの世への思い出になるように、せめてもう一度なりともあなたにお会いしたいのです。 ',
    imageNo: '056',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 57 as KarutaNo,
    creator: '紫式部',
    shoku: { kana: 'めぐりあひて', kanji: 'めぐり逢ひて' },
    niku: { kana: 'みしやそれとも', kanji: '見しやそれとも' },
    sanku: { kana: 'わかぬまに', kanji: 'わかぬ間に' },
    shiku: { kana: 'くもがくれにし', kanji: '雲隠れにし' },
    kekku: { kana: 'よはのつきかな', kanji: '夜半の月かな' },
    translation:
      '久しぶりにめぐり会ったのに、それがあなたかどうかも分からない間に帰ってしまうなど、まるで (早くも) 雲に 隠れてしまった夜中の月のようではありませんか。',
    imageNo: '057',
    kimariji: 1,
    color: 'blue',
  },
  {
    no: 58 as KarutaNo,
    creator: '大弐三位',
    shoku: { kana: 'ありまやま', kanji: '有馬山' },
    niku: { kana: 'ゐなのささはら', kanji: '猪名の笹原' },
    sanku: { kana: 'かぜふけば', kanji: '風吹けば' },
    shiku: { kana: 'いでそよひとを', kanji: 'いでそよ人を' },
    kekku: { kana: 'わすれやはする', kanji: '忘れやはする' },
    translation:
      '有馬山のふもとにある猪名の笹原に風が吹くと、笹の葉がそよそよと鳴りますが、そうです、その音のように、 どうしてあなたを忘れたりするも のでしょうか。',
    imageNo: '058',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 59 as KarutaNo,
    creator: '赤染衛門',
    shoku: { kana: 'やすらはで', kanji: 'やすらはで' },
    niku: { kana: 'ねなましものを', kanji: '寝なましものを' },
    sanku: { kana: 'さよふけて', kanji: '小夜更けて' },
    shiku: { kana: 'かたぶくまでの', kanji: 'かたぶくまでの' },
    kekku: { kana: 'つきをみしかな', kanji: '月を見しかな' },
    translation:
      '(あなたが来ないと知っていたら) さっさと寝てしまえばよかったものを､(あなたの約束を信じて待っていたら) とうとう明け方の月が西に傾くまで眺めてしまいました。',
    imageNo: '059',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 60 as KarutaNo,
    creator: '小式部内侍',
    shoku: { kana: 'おほえやま', kanji: '大江山' },
    niku: { kana: 'いくののみちの', kanji: 'いく野の道の' },
    sanku: { kana: 'とほければ', kanji: '遠ければ' },
    shiku: { kana: 'まだふみもみず', kanji: 'まだふみも見ず' },
    kekku: { kana: 'あまのはしだて', kanji: '天の橋立' },
    translation:
      '(母のいる丹後の国へは) 大江山を越え、生野を通って行かなければならない遠い道なので、まだ天橋立へは行ったことがありません。 (ですから、そこに住む母からの手紙など、まだ見ようはずもありません)',
    imageNo: '060',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 61 as KarutaNo,
    creator: '伊勢大輔',
    shoku: { kana: 'いにしへの', kanji: 'いにしへの' },
    niku: { kana: 'ならのみやこの', kanji: '奈良の都の' },
    sanku: { kana: 'やへざくら', kanji: '八重桜' },
    shiku: { kana: 'けふここのへに', kanji: 'けふ九重に' },
    kekku: { kana: 'にほひぬるかな', kanji: 'にほひぬるかな' },
    translation:
      '昔、奈良の都で咲き誇っていた八重桜が、今日はこの宮中で、いっそう美しく咲き誇っているではありませんか。',
    imageNo: '061',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 62 as KarutaNo,
    creator: '清少納言',
    shoku: { kana: 'よをこめて', kanji: '夜をこめて' },
    niku: { kana: 'とりのそらねは', kanji: '鳥の空音は' },
    sanku: { kana: 'はかるとも', kanji: 'はかるとも' },
    shiku: { kana: 'よにあふさかの', kanji: 'よに逢坂の' },
    kekku: { kana: 'せきはゆるさじ', kanji: '関はゆるさじ' },
    translation:
      '夜の明けないうちに、鶏の鳴き声を真似て夜明けたとだまそうとしても、(あの中国の函谷関ならいざ知らず、あなたとわたしの間にある) この逢坂(おおさか）の関は、決して開くことはありません。',
    imageNo: '062',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 63 as KarutaNo,
    creator: '左京大夫道雅',
    shoku: { kana: 'いまはただ', kanji: '今はただ' },
    niku: { kana: 'おもひたえなむ', kanji: '思ひ絶えなむ' },
    sanku: { kana: 'とばかりを', kanji: 'とばかりを' },
    shiku: { kana: 'ひとづてならで', kanji: '人づてならで' },
    kekku: { kana: 'いふよしもがな', kanji: 'いふよしもがな' },
    translation:
      '今はもう、あなたのことはきっぱりと思い切ってしまおうと決めましたが、そのことだけを人づてでなく、直接 あなたに伝える方法があればいいのですが。',
    imageNo: '063',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 64 as KarutaNo,
    creator: '権中納言定頼',
    shoku: { kana: 'あさぼらけ', kanji: '朝ぼらけ' },
    niku: { kana: 'うぢのかはぎり', kanji: '宇治の川霧' },
    sanku: { kana: 'たえだえに', kanji: 'たえだえに' },
    shiku: { kana: 'あらはれわたる', kanji: 'あらはれわたる' },
    kekku: { kana: 'せぜのあじろぎ', kanji: '瀬々の網代木' },
    translation:
      'ほのぼのと夜が明けるころ、宇治川に立ちこめた川霧が切れ切れに晴れてきて、瀬ごとに立っている網代木が次第にあらわれてくる景色は、何ともおもしろいものではないか。',
    imageNo: '064',
    kimariji: 6,
    color: 'orange',
  },
  {
    no: 65 as KarutaNo,
    creator: '相模',
    shoku: { kana: 'うらみわび', kanji: '恨みわび' },
    niku: { kana: 'ほさぬそでだに', kanji: 'ほさぬ袖だに' },
    sanku: { kana: 'あるものを', kanji: 'あるものを' },
    shiku: { kana: 'こひにくちなむ', kanji: '恋に朽ちなむ' },
    kekku: { kana: 'なこそをしけれ', kanji: '名こそ惜しけれ' },
    translation:
      'あなたの冷たさを恨み、流す涙でかわくひまさえもない袖でさえ口惜いのに、こ の恋のために、(つまらぬ噂で) わたしの名が落ちてしまうのは、なんとも口惜しいことです。',
    imageNo: '065',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 66 as KarutaNo,
    creator: '前大僧正行尊',
    shoku: { kana: 'もろともに', kanji: 'もろともに' },
    niku: { kana: 'あはれとおもへ', kanji: 'あはれと思へ' },
    sanku: { kana: 'やまざくら', kanji: '山桜' },
    shiku: { kana: 'はなよりほかに', kanji: '花よりほかに' },
    kekku: { kana: 'しるひともなし', kanji: '知る人もなし' },
    translation:
      '私がおまえを愛しむように、おまえも私を愛しいと 思ってくれよ、山桜。 (こんな山奥では) おまえの他には私を知る人は誰もいないのだから。',
    imageNo: '066',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 67 as KarutaNo,
    creator: '周防内侍',
    shoku: { kana: 'はるのよの', kanji: '春の夜の' },
    niku: { kana: 'ゆめばかりなる', kanji: '夢ばかりなる' },
    sanku: { kana: 'たまくらに', kanji: '手枕に' },
    shiku: { kana: 'かひなくたたむ', kanji: 'かひなく立たむ' },
    kekku: { kana: 'なこそをしけれ', kanji: '名こそをしけれ' },
    translation:
      '春の夜のはかない夢のように、(僅かばかりの時間でも) あなたの腕を枕にしたりして、それでつまらない噂が立つことにでもなれば、それがまことに残念なのです。',
    imageNo: '067',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 68 as KarutaNo,
    creator: '三条院',
    shoku: { kana: 'こころにも', kanji: '心にも' },
    niku: { kana: 'あらでうきよに', kanji: 'あらでうき世に' },
    sanku: { kana: 'ながらへば', kanji: 'ながらへば' },
    shiku: { kana: 'こひしかるべき', kanji: '恋しかるべき' },
    kekku: { kana: 'よはのつきかな', kanji: '夜半の月かな' },
    translation:
      '(もはやこの世に望みもないが) 心にもなく、このつらい浮世を生きながらえたなら、さぞかしこの宮中で見た夜の月が恋しく思 い出されることであろうなぁ。',
    imageNo: '068',
    kimariji: 4,
    color: 'green',
  },
  {
    no: 69 as KarutaNo,
    creator: '能因法師',
    shoku: { kana: 'あらしふく', kanji: '嵐吹く' },
    niku: { kana: 'みむろのやまの', kanji: '三室の山の' },
    sanku: { kana: 'もみぢばは', kanji: 'もみぢ葉は' },
    shiku: { kana: 'たつたのかはの', kanji: '竜田の川の' },
    kekku: { kana: 'にしきなりけり', kanji: '錦なりけり' },
    translation:
      '嵐が吹き散らした三室の山の紅葉の葉が、龍田川 に一面に散っているが、まるで錦の織物のように美しいではないか。',
    imageNo: '069',
    kimariji: 3,
    color: 'blue',
  },
  {
    no: 70 as KarutaNo,
    creator: '良選法師',
    shoku: { kana: 'さびしさに', kanji: 'さびしさに' },
    niku: { kana: 'やどをたちいでて', kanji: '宿を立ち出でて' },
    sanku: { kana: 'ながむれば', kanji: 'ながむれば' },
    shiku: { kana: 'いづこもおなじ', kanji: 'いづくも同じ' },
    kekku: { kana: 'あきのゆふぐれ', kanji: '秋の夕暮' },
    translation: '寂しくて家を出てあたりを眺めてはみたが、この秋の夕暮れの寂しさはどこも同じであるものだ。',
    imageNo: '070',
    kimariji: 1,
    color: 'blue',
  },
  {
    no: 71 as KarutaNo,
    creator: '大納言経信',
    shoku: { kana: 'ゆふされば', kanji: '夕されば' },
    niku: { kana: 'かどたのいなば', kanji: '門田の稲葉' },
    sanku: { kana: 'おとづれて', kanji: 'おとづれて' },
    shiku: { kana: 'あしのまろやに', kanji: '蘆のまろやに' },
    kekku: { kana: 'あきかぜぞふく', kanji: '秋風ぞ吹く' },
    translation: '夕方になると、家の前にある田の稲葉を音をたてて、 葦葺きのそまつな小屋に秋風が吹き訪れることよ。',
    imageNo: '071',
    kimariji: 2,
    color: 'green',
  },
  {
    no: 72 as KarutaNo,
    creator: '祐子内親王家紀伊',
    shoku: { kana: 'おとにきく', kanji: '音に聞く' },
    niku: { kana: 'たかしのはまの', kanji: '高師の浜の' },
    sanku: { kana: 'あだなみは', kanji: 'あだ波は' },
    shiku: { kana: 'かけじやそでの', kanji: 'かけじや袖の' },
    kekku: { kana: 'ぬれもこそすれ', kanji: 'ぬれもこそすれ' },
    translation:
      '評判の高い高師の浜の寄せてはかえす波で、 袖を濡らさないようにしましょう。\r(移り気だと、噂の高いあなたに思いをかけて、わたしの袖を濡らさないように)',
    imageNo: '072',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 73 as KarutaNo,
    creator: '前権中納言匡房',
    shoku: { kana: 'たかさごの', kanji: '高砂の' },
    niku: { kana: 'をのへのさくら', kanji: '尾上の桜' },
    sanku: { kana: 'さきにけり', kanji: '咲きにけり' },
    shiku: { kana: 'とやまのかすみ', kanji: '外山の霞' },
    kekku: { kana: 'たたずもあらなむ', kanji: '立たずもあらなむ' },
    translation:
      '高砂の峰にも桜の花が咲いたようだから､(その桜を見たいので) 手前の山の霞よ､どうか立たないようにしてくれないか。',
    imageNo: '073',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 74 as KarutaNo,
    creator: '源俊頼朝臣',
    shoku: { kana: 'うかりける', kanji: '憂かりける' },
    niku: { kana: 'ひとをはつせの', kanji: '人を初瀬の' },
    sanku: { kana: 'やまおろしよ', kanji: '山おろしよ' },
    shiku: { kana: 'はげしかれとは', kanji: 'はげしかれとは' },
    kekku: { kana: 'いのらぬものを', kanji: '祈らぬものを' },
    translation:
      '私に冷たかった人の心が変わるようにと、初瀬の観音さまにお祈りしたのだが、初瀬の山おろしよ、そのようにあの人の冷たさがいっそう激しくなれとは祈らなかったではないか…',
    imageNo: '074',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 75 as KarutaNo,
    creator: '藤原基俊',
    shoku: { kana: 'ちぎりおきし', kanji: '契りおきし' },
    niku: { kana: 'させもがつゆを', kanji: 'させもが露を' },
    sanku: { kana: 'いのちにて', kanji: '命にて' },
    shiku: { kana: 'あはれことしの', kanji: 'あはれ今年の' },
    kekku: { kana: 'あきもいぬめり', kanji: '秋もいぬめり' },
    translation:
      'あなたが約束してくださった、させも草についた恵みの露のようなありがたい言葉を、頼みにしておりましたが、それもむなしく、今年の秋もすぎてしまうようです。',
    imageNo: '075',
    kimariji: 4,
    color: 'blue',
  },
  {
    no: 76 as KarutaNo,
    creator: '法性寺入道前関白太政大臣',
    shoku: { kana: 'わたのはら', kanji: 'わたの原' },
    niku: { kana: 'こぎいでてみれば', kanji: '漕ぎ出でて見れば' },
    sanku: { kana: 'ひさかたの', kanji: 'ひさかたの' },
    shiku: { kana: 'くもゐにまがふ', kanji: '雲居にまがふ' },
    kekku: { kana: 'おきつしらなみ', kanji: '沖つ白波' },
    translation:
      '大海原に船を漕ぎ出してみると、遠くの方では、雲と見わけがつかないような白波が立っているのが見える。(まことにおもしろい眺めではないか)',
    imageNo: '076',
    kimariji: 6,
    color: 'blue',
  },
  {
    no: 77 as KarutaNo,
    creator: '崇徳院',
    shoku: { kana: 'せをはやみ', kanji: '瀬を早み' },
    niku: { kana: 'いはにせかるる', kanji: '岩にせかるる' },
    sanku: { kana: 'たきがはの', kanji: '滝川の' },
    shiku: { kana: 'われてもすゑに', kanji: 'われても末に' },
    kekku: { kana: 'あはむとぞおもふ', kanji: '逢はむとぞ思ふ' },
    translation:
      '川の流れが早いので、岩にせき止められた急流が時にはふたつに分かれても、またひとつになるように、わたし達の間も、(今はたとえ人にせき止められていようとも)後にはきっと結ばれるものと思っています。',
    imageNo: '077',
    kimariji: 1,
    color: 'orange',
  },
  {
    no: 78 as KarutaNo,
    creator: '源兼昌',
    shoku: { kana: 'あはぢしま', kanji: '淡路島' },
    niku: { kana: 'かよふちどりの', kanji: 'かよふ千鳥の' },
    sanku: { kana: 'なくこゑに', kanji: '鳴く声に' },
    shiku: { kana: 'いくよねざめぬ', kanji: '幾夜寝覚めぬ' },
    kekku: { kana: 'すまのせきもり', kanji: '須磨の関守' },
    translation: '淡路島から通ってくる千鳥の鳴き声に、幾晩目を覚ましたことであろうか、この須磨の関の関守は…。',
    imageNo: '078',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 79 as KarutaNo,
    creator: '左京大夫顕輔',
    shoku: { kana: 'あきかぜに', kanji: '秋風に' },
    niku: { kana: 'たなびくくもの', kanji: 'たなびく雲の' },
    sanku: { kana: 'たえまより', kanji: '絶え間より' },
    shiku: { kana: 'もれいづるつきの', kanji: 'もれ出づる月の' },
    kekku: { kana: 'かげのさやけさ', kanji: '影のさやけさ' },
    translation:
      '秋風に吹かれてたなびいている雲の切れ間から、もれでてくる月の光は、なんと清らかで澄みきっていることであろう。',
    imageNo: '079',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 80 as KarutaNo,
    creator: '待賢門院堀河',
    shoku: { kana: 'ながからむ', kanji: '長からむ' },
    niku: { kana: 'こころもしらず', kanji: '心も知らず' },
    sanku: { kana: 'くろかみの', kanji: '黒髪の' },
    shiku: { kana: 'みだれてけさは', kanji: '乱れて今朝は' },
    kekku: { kana: 'ものをこそおもへ', kanji: '物をこそ思へ' },
    translation:
      'あなたの心は末永くまで決して変わらないかどうか、わたしの黒髪が乱れているように、わたしの心も乱れて、今朝は物思いに沈んでおります。',
    imageNo: '080',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 81 as KarutaNo,
    creator: '後徳大寺左大臣',
    shoku: { kana: 'ほととぎす', kanji: 'ほととぎす' },
    niku: { kana: 'なきつるかたを', kanji: '鳴きつる方を' },
    sanku: { kana: 'ながむれば', kanji: 'ながむれば' },
    shiku: { kana: 'ただありあけの', kanji: 'ただ有明の' },
    kekku: { kana: 'つきぞのこれる', kanji: '月ぞ残れる' },
    translation:
      'ほととぎすの鳴き声が聞こえたので、その方に目をやってみたが、(その姿はもう見えず) 空には有明の月が残っているばかりであった。',
    imageNo: '081',
    kimariji: 1,
    color: 'yellow',
  },
  {
    no: 82 as KarutaNo,
    creator: '道因法師',
    shoku: { kana: 'おもひわび', kanji: '思ひわび' },
    niku: { kana: 'さてもいのちは', kanji: 'さても命は' },
    sanku: { kana: 'あるものを', kanji: 'あるものを' },
    shiku: { kana: 'うきにたへぬは', kanji: '憂きに堪へぬは' },
    kekku: { kana: 'なみだなりけり', kanji: '涙なりけり' },
    translation:
      'つれない人のことを思い、これほど悩み苦しんでいても、命だけはどうにかあるものの、この辛さに耐えかねるのは (次から次へと流れる) 涙であることだ。',
    imageNo: '082',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 83 as KarutaNo,
    creator: '皇太后宮大夫俊成',
    shoku: { kana: 'よのなかよ', kanji: '世の中よ' },
    niku: { kana: 'みちこそなけれ', kanji: '道こそなけれ' },
    sanku: { kana: 'おもひいる', kanji: '思ひ入る' },
    shiku: { kana: 'やまのおくにも', kanji: '山の奥にも' },
    kekku: { kana: 'しかぞなくなる', kanji: '鹿ぞ鳴くなる' },
    translation:
      '世の中というものは逃れる道がないものだ。(この山奥に逃れてきたものの) この山奥でも、(辛いことがあったのか) 鹿が鳴いているではないか。',
    imageNo: '083',
    kimariji: 5,
    color: 'pink',
  },
  {
    no: 84 as KarutaNo,
    creator: '藤原清輔朝臣',
    shoku: { kana: 'ながらへば', kanji: '長らへば' },
    niku: { kana: 'またこのごろや', kanji: 'またこのごろや' },
    sanku: { kana: 'しのばれむ', kanji: 'しのばれむ' },
    shiku: { kana: 'うしとみしよぞ', kanji: '憂しと見し世ぞ' },
    kekku: { kana: 'いまはこひしき', kanji: '今は恋しき' },
    translation:
      'この先生きながらえるならば、今のつらいことなども懐かしく思い出されるのだろうか。昔は辛いと思っていたことが、今では懐かしく思い出されるのだから。',
    imageNo: '084',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 85 as KarutaNo,
    creator: '俊恵法師',
    shoku: { kana: 'よもすがら', kanji: '夜もすがら' },
    niku: { kana: 'ものおもふころは', kanji: '物思ふころは' },
    sanku: { kana: 'あけやらで', kanji: '明けやらで' },
    shiku: { kana: 'ねやのひまさへ', kanji: '閨のひまさへ' },
    kekku: { kana: 'つれなかりけり', kanji: 'つれなかりけり' },
    translation:
      '一晩中恋しい人を思って悩んでいるので、早く夜が明けたらよいと思っているのですが、なかなか夜は明けず、寝室の隙間さえもわたしにつれなく感じられます。',
    imageNo: '085',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 86 as KarutaNo,
    creator: '西行法師',
    shoku: { kana: 'なげけとて', kanji: '嘆けとて' },
    niku: { kana: 'つきやはものを', kanji: '月やは物を' },
    sanku: { kana: 'おもはする', kanji: '思はする' },
    shiku: { kana: 'かこちがほなる', kanji: 'かこち顔なる' },
    kekku: { kana: 'わがなみだかな', kanji: 'わが涙かな' },
    translation:
      '嘆き悲しめと月はわたしに物思いをさせるのだろうか。 いや、そうではあるまい。本当は恋の悩みの所為なのに、まるで月の仕業であるかのように流れるわたしの涙ではないか。',
    imageNo: '086',
    kimariji: 3,
    color: 'pink',
  },
  {
    no: 87 as KarutaNo,
    creator: '寂蓮法師',
    shoku: { kana: 'むらさめの', kanji: '村雨の' },
    niku: { kana: 'つゆもまだひぬ', kanji: '露もまだひぬ' },
    sanku: { kana: 'まきのはに', kanji: '槇の葉に' },
    shiku: { kana: 'きりたちのぼる', kanji: '霧たちのぼる' },
    kekku: { kana: 'あきのゆふぐれ', kanji: '秋の夕ぐれ' },
    translation:
      'あわただしく通り過ぎたにわか雨が残した露もまだ乾ききらないのに、槇の葉にはもう霧が立ちのぼっていく秋の夕暮れである。(なんとももの寂しいことではないか)',
    imageNo: '087',
    kimariji: 1,
    color: 'yellow',
  },
  {
    no: 88 as KarutaNo,
    creator: '皇嘉門院別当',
    shoku: { kana: 'なにはえの', kanji: '難波江の' },
    niku: { kana: 'あしのかりねの', kanji: '蘆のかりねの' },
    sanku: { kana: 'ひとよゆゑ', kanji: 'ひとよゆゑ' },
    shiku: { kana: 'みをつくしてや', kanji: 'みをつくしてや' },
    kekku: { kana: 'こひわたるべき', kanji: '恋ひわたるべき' },
    translation:
      '難波の入江に生えている、芦を刈った根のひと節ほどの短いひと夜でしたが、わたしはこれからこの身をつくして、あなたに恋しなければならないのでしょうか。',
    imageNo: '088',
    kimariji: 4,
    color: 'orange',
  },
  {
    no: 89 as KarutaNo,
    creator: '式子内親王',
    shoku: { kana: 'たまのをよ', kanji: '玉の緒よ' },
    niku: { kana: 'たえなばたえね', kanji: '絶えなば絶えね' },
    sanku: { kana: 'ながらへば', kanji: 'ながらへば' },
    shiku: { kana: 'しのぶることの', kanji: '忍ぶることの' },
    kekku: { kana: 'よわりもぞする', kanji: '弱りもぞする' },
    translation:
      'わたしの命よ、絶えることなら早く絶えてほしい。このまま生きながらえていると、耐え忍んでいるわたしの心も弱くなってしまい、 秘めている思いが人に知られてしまうことになろうから。',
    imageNo: '089',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 90 as KarutaNo,
    creator: '殷富門院大輔',
    shoku: { kana: 'みせばやな', kanji: '見せばやな' },
    niku: { kana: 'をじまのあまの', kanji: '雄島のあまの' },
    sanku: { kana: 'そでだにも', kanji: '袖だにも' },
    shiku: { kana: 'ぬれにぞぬれし', kanji: '濡れにぞ濡れし' },
    kekku: { kana: 'いろはかはらず', kanji: '色はかはらず' },
    translation:
      '(涙で色が変わってしまった) わたしの袖をあなたにお見せしたいものです。あの雄島の漁夫の袖でさえ、毎日波しぶきに濡れていても、少しも変わらないものなのに。',
    imageNo: '090',
    kimariji: 2,
    color: 'orange',
  },
  {
    no: 91 as KarutaNo,
    creator: '後京極摂政前太政大臣',
    shoku: { kana: 'きりぎりす', kanji: 'きりぎりす' },
    niku: { kana: 'なくやしもよの', kanji: '鳴くや霜夜の' },
    sanku: { kana: 'さむしろに', kanji: 'さむしろに' },
    shiku: { kana: 'ころもかたしき', kanji: '衣片敷き' },
    kekku: { kana: 'ひとりかもねむ', kanji: 'ひとりかも寝む' },
    translation:
      'こおろぎがしきりに鳴いている霜の降るこの寒い夜に、むしろの上に衣の片袖を敷いて、わたしはたったひとり寂しく寝るのだろうか。',
    imageNo: '091',
    kimariji: 2,
    color: 'blue',
  },
  {
    no: 92 as KarutaNo,
    creator: '二条院讃岐',
    shoku: { kana: 'わがそでは', kanji: 'わが袖は' },
    niku: { kana: 'しほひにみえぬ', kanji: '潮干に見えぬ' },
    sanku: { kana: 'おきのいしの', kanji: '沖の石の' },
    shiku: { kana: 'ひとこそしらね', kanji: '人こそ知らね' },
    kekku: { kana: 'かわくまもなし', kanji: '乾く間もなし' },
    translation:
      'わたしの袖は､潮が引いたときも水面に見えない沖にあるあの石のように､人は知らないでしょうが､(恋のために流す涙で) 乾くひまさえありません｡',
    imageNo: '092',
    kimariji: 3,
    color: 'green',
  },
  {
    no: 93 as KarutaNo,
    creator: '鎌倉右大臣',
    shoku: { kana: 'よのなかは', kanji: '世の中は' },
    niku: { kana: 'つねにもがもな', kanji: '常にもがもな' },
    sanku: { kana: 'なぎさこぐ', kanji: '渚漕ぐ' },
    shiku: { kana: 'あまのをぶねの', kanji: 'あまの小舟の' },
    kekku: { kana: 'つなでかなしも', kanji: '綱手かなしも' },
    translation:
      'この世の中はいつまでも変わらないでいてほしいものだ。渚にそって漕いでいる、漁師の小船をひき綱で引いている風情はいいものだからなぁ…',
    imageNo: '093',
    kimariji: 5,
    color: 'green',
  },
  {
    no: 94 as KarutaNo,
    creator: '参議雅経',
    shoku: { kana: 'みよしのの', kanji: 'み吉野の' },
    niku: { kana: 'やまのあきかぜ', kanji: '山の秋風' },
    sanku: { kana: 'さよふけて', kanji: '小夜ふけて' },
    shiku: { kana: 'ふるさとさむく', kanji: 'ふるさと寒く' },
    kekku: { kana: 'ころもうつなり', kanji: '衣うつなり' },
    translation:
      '吉野の山の秋風に、夜もしだいに更けてきて、都があったこの里では、衣をうつ砧(きぬた)の音が寒々と身にしみてくることだ。',
    imageNo: '094',
    kimariji: 2,
    color: 'yellow',
  },
  {
    no: 95 as KarutaNo,
    creator: '前大僧正慈円',
    shoku: { kana: 'おほけなく', kanji: 'おほけなく' },
    niku: { kana: 'うきよのたみに', kanji: 'うき世の民に' },
    sanku: { kana: 'おほふかな', kanji: 'おほふかな' },
    shiku: { kana: 'わがたつそまに', kanji: 'わがたつ杣に' },
    kekku: { kana: 'すみぞめのそで', kanji: '墨染の袖' },
    translation:
      '身のほど知らずと言われるかもしれないが、(この悲しみに満ちた) 世の中の人々の上に、墨染の袖を被いかけよう。 (比叡山に出家したわたしが平穏を願って)',
    imageNo: '095',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 96 as KarutaNo,
    creator: '入道前太政大臣',
    shoku: { kana: 'はなさそふ', kanji: '花さそふ' },
    niku: { kana: 'あらしのにはの', kanji: '嵐の庭の' },
    sanku: { kana: 'ゆきならで', kanji: '雪ならで' },
    shiku: { kana: 'ふりゆくものは', kanji: 'ふりゆくものは' },
    kekku: { kana: 'わがみなりけり', kanji: 'わが身なりけり' },
    translation:
      '(降っているのは) 嵐が庭に散らしている花吹雪ではなくて、降っているのは、実は歳をとっていくわが身なのだなぁ。',
    imageNo: '096',
    kimariji: 3,
    color: 'yellow',
  },
  {
    no: 97 as KarutaNo,
    creator: '権中納言定家',
    shoku: { kana: 'こぬひとを', kanji: '来ぬ人を' },
    niku: { kana: 'まつほのうらの', kanji: 'まつほの浦の' },
    sanku: { kana: 'ゆふなぎに', kanji: '夕なぎに' },
    shiku: { kana: 'やくやもしほの', kanji: '焼くや藻塩の' },
    kekku: { kana: 'みもこがれつつ', kanji: '身もこがれつつ' },
    translation:
      'どれほど待っても来ない人を待ち焦がれているのは､松帆の浦の夕凪のころに焼かれる藻塩のように、わが身も恋い焦がれて苦しいものだ。',
    imageNo: '097',
    kimariji: 2,
    color: 'pink',
  },
  {
    no: 98 as KarutaNo,
    creator: '従二位家隆',
    shoku: { kana: 'かぜそよぐ', kanji: '風そよぐ' },
    niku: { kana: 'ならのをがはの', kanji: 'ならの小川の' },
    sanku: { kana: 'ゆふぐれは', kanji: '夕暮は' },
    shiku: { kana: 'みそぎぞなつの', kanji: 'みそぎぞ夏の' },
    kekku: { kana: 'しるしなりける', kanji: 'しるしなりける' },
    translation:
      '風がそよそよと楢(なら)の葉を吹きわたるこのならの小川の夕方は､(もうすっかりと秋のような気配だが) 川辺の禊祓（みそぎはらい）を見ると､まだ夏であるのだなぁ｡',
    imageNo: '098',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 99 as KarutaNo,
    creator: '後鳥羽院',
    shoku: { kana: 'ひともをし', kanji: '人もをし' },
    niku: { kana: 'ひともうらめし', kanji: '人もうらめし' },
    sanku: { kana: 'あぢきなく', kanji: 'あぢきなく' },
    shiku: { kana: 'よをおもふゆゑに', kanji: '世を思ふゆゑに' },
    kekku: { kana: 'ものおもふみは', kanji: '物思ふ身は' },
    translation:
      '人が愛しくも思われ､また恨めしく思われたりするのは、(歎かわしいことではあるが) この世をつまらなく思う、もの思いをする自分にあるのだなぁ。',
    imageNo: '099',
    kimariji: 3,
    color: 'orange',
  },
  {
    no: 100 as KarutaNo,
    creator: '順徳院',
    shoku: { kana: 'ももしきや', kanji: 'ももしきや' },
    niku: { kana: 'ふるきのきばの', kanji: '古き軒端の' },
    sanku: { kana: 'しのぶにも', kanji: 'しのぶにも' },
    shiku: { kana: 'なほあまりある', kanji: 'なほあまりある' },
    kekku: { kana: 'むかしなりけり', kanji: '昔なりけり' },
    translation:
      '宮中の古びた軒先に忍んで生えている草を見るにつけて、いくら偲（しの）んでも偲びきれないのは、昔の（よく治まっていた）御代（みよ、天皇の治世のこと）であることよ。',
    imageNo: '100',
    kimariji: 2,
    color: 'blue',
  },
] as const;
